---
perforce::server::user: perforce
perforce::server::password: password
perforce::server::p4root: /var/local/p4root
perforce::server::p4journal: /var/log/journal
perforce::server::p4err: /var/log/p4err
perforce::server::p4port: 1666
